version: '3.8'

services:
  oc-mirror-web-app:
    build: .
    container_name: oc-mirror-web-app
    ports:
      - "3000:3001"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount pull secret if available
      - ./pull-secret.json:/app/pull-secret.json:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
      - STORAGE_DIR=/app/data
      - OC_MIRROR_CACHE_DIR=/app/data/cache
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/system/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - oc-mirror-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: oc-mirror-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - oc-mirror-web-app
    restart: unless-stopped
    networks:
      - oc-mirror-network
    profiles:
      - production

networks:
  oc-mirror-network:
    driver: bridge

volumes:
  data:
    driver: local 